spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://192.168.9.14:12345/owtdb
      database: owtdb
      username: test
      password: test1234
  cloud:
    function:
        definition: tx;rx
    stream:
      bindings:
        tx-out-0:
          binder: rabbit
          destination: owtRpc
        rx-in-0:
          binder: rabbit
          destination: owtRpc
          group: management-${QUEUE_NAME:queue}
      rabbit:
        bindings:
          rx-in-0:
            consumer:
              exchange-type: direct
              exchangeDurable: false
              exchangeAutoDelete: true
              #management api가 scalable하려면 중복되지 않는 값을 사용해야 한다
              binding-routing-key: ${BINDING_ROUTING_KEY:management}
          tx-out-0:
            producer:
              exchangeDurable: false
              exchangeAutoDelete: true
              exchange-type: direct
              routing-key-expression: headers['routingKey']

  rabbitmq:
    host: 192.168.9.14
    port: 54321
    username: test
    password: test1234

server:
  address: 192.168.9.13
  port: 8080

#mongodb retry
mongodb:
  transaction:
    enable: false
  retry:
    times: 5
    initialDelay: 100
    maxDelay: 1000

logging:
  level:
    org.springframework: DEBUG
    org.springframework.web: DEBUG
  file:
    name: logs/log_dev.log
