spring:
  data:
    mongodb:
      uri: mongodb://192.168.9.14:12345
      database: owtdb
      username: test
      password: test1234
  cloud:
    function:
        definition: tx;rx
    stream:
      bindings:
        tx-out-0:
          binder: rabbit
          destination: owtRpc
        rx-in-0:
          binder: rabbit
          destination: owtRpc
          #management api가 scalable하려면 중복되지 않는 값을 사용해야 한다
          group: test-routing-key #${random.uuid}
      rabbit:
        bindings:
          rx-in-0:
            consumer:
              exchange-type: direct
              binding-routing-key: ${spring.cloud.stream.bindings.rx-in-0.group}
          tx-out-0:
            producer:
              exchangeDurable: false
              exchangeAutoDelete: true
              exchange-type: direct
              routing-key-expression: headers['routeTo']

  rabbitmq:
    host: 192.168.9.14
    port: 54321
    username: test
    password: test1234

server:
  address: localhost
  port: 8080

#mongodb retry
mongodb:
  retry:
    times: 5
    initialDelay: 100
    maxDelay: 1000